# Generated by Django 5.2.6 on 2025-12-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
